### ISSUE TITLE
Question: relating to ora2pg

### ISSUE THREAD

**Issue by MichaelDBA** [cybertec-postgresql/ora_migrator#1]
Wow, very interested in this new ora to pg tool.  I'm wondering if you all used any procedural coding conversion logic from ora2pg, or some other existing tool out there.  Converting procedural stuff from oracle to postgresql is a not perfect science at this point, so just wondering how well your tool might compare to others in this regard.

**Comment by laurenz** [comment]
In the spirit of &ldquo;keep it simple&rdquo; I am not trying to convert PL/SQL code at all.

My goal is to do automatically what can be done automatically with a certain reliability and leave the rest for manual editing.

It is my personal believe that automatic conversion of any non-trivial code will not work and leave you with something where you'll have to go back to the original source anyway, so why bother. I may be wrong, but I think it would require massive AI.
