### ISSUE TITLE
Queries on limitation in Ora_Migrator

### ISSUE THREAD

**Issue by Arun-V-S** [cybertec-postgresql/ora_migrator#10]
Hi Laurenz/Team, 

I have 4 questions with respect to ORA Migrator limitations. I have some observations on using the ora_migrator. Let me share with you and get your view on it. I have some some queries as well that are listed below. Hoping for your reply. Thanks in advance.

- Is there any table volume limitation in migration from Oracle to Postgres? **Test 1 :** I tried migrating schema that has a table with 110GB of data(0.9 million rows of dummy data with 2 columns). It is working fine and can able to migrate successfully in less than 2.5 hours. **Test 2:** But for a single table with 125GB of data(60 million rows of dummy data), Migration is happening which is an never ending story(almost 8 hours+) and no errors were thrown out. I verified that the migration is never ending by checking the CPU Utilization in Postgres and its between 0.3% to 6%. I am clear that Postgres instance have sufficient space so that Oracle tables has to be migrated. (Postgres instance spec- 8 cores, 16GB RAM, 240GB volume). I have tried Both oracle_migrate and oracle_materialize for the second test.

- I am clear that, we can able to do selective table migration in a schema with oracle_materialize to increase performance. Is it possible to migrate a single table in parts? (As the data volume is huge for a one particular table, I suspect above 120GB of data, Ora_migrator is not migrating the single table.)

- Will Ora_migrator support migrating partitioning and sub-partioning of tables, index and LOBS?

- Will Ora_migrator support migrating package, package body and materialized views?

Thanks,
Arun V S

**Comment by laurenz** [comment]
These are good questions!

- The difference in migration time for the two tables of almost equal size is indeed surprising.
  The only explanation I have is that the slow table contains one or more LOBs. It is a known limitation of Oracle that row prefetching doesn't work for tables with LOBs.

- There is no support for migration of one table in parts, and I have no plans of adding it.
  I don't know how that should be done &ldquo;automatically&rdquo;, but you can consider ora_migrator as a toolbox with which you can develop your migration.

  You can write your own function that can migrate part of a table. The difficult part is to find a condition that separates parts of the table in a way that the condition can be pushed down by oracle_fdw.

- I don't think that ora_migrator will have specific support for partitioning in the forseeable future. Oracle's partitioning is so powerful, and PostgreSQL's partitioning (still) so simple that any attempt to automatically translate the former to the latter will have to fail in most cases.

  My design paradigm is to keep it simple. ora_migrator automates the parts that can be automatized easily, for the other parts you have to build a custom solution.

- There won't be any support for migrating PL/SQL code. However, migrating materialized views is definitely an option. The only problem is that &ndash; again &ndash; Oracle's materialized views are much more powerful and support things like update on commit.

**Comment by Arun-V-S** [comment]
Thanks for your quick reply. 

The table that I have used for the migration has no LOBs. It has only varchars and number(30 columns). Still I cannot able to migrate 125 GB of data for one table.

If we have more GBs of data in schema level, we can able to migrate successfully. But, if one of the table itself have 125GB of data, then there is an issue at migration for me. **Is there any benchmark result that you can share me upto how many GBs of data for a single table is success (if you have any).**

I understand that, for Materialized view, partitioning and packages, we need to build a custom solution or move manually. Is my understanding is right? I really appreciate your help. Thank again.

**Comment by laurenz** [comment]
Yes, what ora_migrator cannot migrate, you have to migrate yourself.
With PL/SQL this can be a lot of trouble (but I doubt that you can avoid that with any tool), but with materialized views it should not be too complicated.

Unfortunately I have no benchmark &ndash; the databases I have migrated so far didn't have tables of that size.

You could try setting the `prefetch` option on the foreign table to a higher value before migrating is; maybe that can help.

What data types does the table use?
