### ISSUE TITLE
Turn RAISE NOTICE to function calls

### ISSUE THREAD

**Issue by postgresql007** [cybertec-postgresql/ora_migrator#14]
Currently we do RAISE NOTICE to fire out log. Can we send logs into a table AND do a RAISE NOTICE? it is easier for UI people to visualize.

**Comment by laurenz** [comment]
I have decided only to use a temporary table and I only log the errors that happen during migration.
Any tool that calls `ora_migrator` will probably not call `oracle_migrate`, but rather the indicidual functions, so it knows which step is currently being performed.
