### ISSUE TITLE
NCLOB to text

### ISSUE THREAD

**Issue by beton-mischa** [cybertec-postgresql/ora_migrator#17]
Hi @laurenz,

i am currently testing the limits of ora_migrator and noticed that nclob is not really handled well.
After oracle_migrate_prepare() it's listed in pgsql_stage.columns with oracle_type: "NCLOB" and type: "text", which would be fine since my example contains just a random string. 
But when go on with migrating an error "DETAIL:  column "nclob_1" of foreign table "t_types_2" cannot be converted to or from Oracle data type".
Is this intended behaviour?

**Comment by laurenz** [comment]
Yes.

The [README of oracle_fdw](https://github.com/laurenz/oracle_fdw) says that `NCLOB` is not supported:

> NCLOB is currently not supported because Oracle cannot automatically convert
> it to the client encoding.

Since ora_migrator uses oracle_fdw, it cannot convert such data.

You could try do define a foreign table like this:

    ... OPTIONS (table '(SELECT CAST(nc AS varchar2(4000)) FROM tab)')

but I am not sure if that works with `NCLOB`s.

**Comment by beton-mischa** [comment]
Hi,

oh ok, seems like i missed that.
I'll try your suggestion and thanks for the quick reply.
