### ISSUE TITLE
debugging option 

### ISSUE THREAD

**Issue by seadba** [cybertec-postgresql/ora_migrator#2]
is there a flag that will show more output from the main call?  i have an oracle schema with 9 tables - the migrator user has full privileges and can create a foreign table for that schema - however when i run the main process it doesnt fail but doesnt migrate the tables either   pg v 9.6.8

    You are now connected to database "btpg96" as user "migrator".
    btpg96=#  create foreign table PGJOBS (
    btpg96(# job_id character varying(10),
    btpg96(# job_title character varying(35))
    btpg96-# server btoradev options (schema 'HR',table 'PGJOBS');
    CREATE FOREIGN TABLE
    btpg96=# select count(*) from PGJOBS;
     count
    -------
        19
    (1 row)

    btpg96=# SELECT oracle_migrate(server => 'btoradev', only_schemas=> '{HR}');
    NOTICE:  Creating staging schemas "ora_stage" and "pgsql_stage" ...
    NOTICE:  Creating Oracle metadata views in schema "ora_stage" ...
    NOTICE:  Copy definitions to PostgreSQL staging schema "pgsql_stage" ...
    NOTICE:  Creating schemas ...
    NOTICE:  Creating sequences ...
    NOTICE:  Creating foreign tables ...
    NOTICE:  Creating UNIQUE and PRIMARY KEY constraints ...
    NOTICE:  Creating FOREIGN KEY constraints ...
    NOTICE:  Creating CHECK constraints ...
    NOTICE:  Creating indexes ...
    NOTICE:  Setting column default values ...
    NOTICE:  Dropping staging schemas ...
    NOTICE:  Migration completed with 0 errors.
     oracle_migrate
    ----------------
                  0

**Comment by laurenz** [comment]
orac_migrator does not attempt to migrate Oracle system and test schemas &mdash; I had assumed that this would only cause pain in real applications.

`HR` is an Oracle test schema, so it is silently ignored.

Here is the current list of excluded schemas:

    ANONYMOUS
    APEX_PUBLIC_USER
    APEX_030200
    APEX_040000
    APPQOSSYS
    AURORA$JIS$UTILITY$
    AURORA$ORB$UNAUTHENTICATED
    BI
    CTXSYS
    DBSNMP
    DIP
    DMSYS
    EXFSYS
    FLOWS_FILES
    HR
    IX
    LBACSYS
    MDDATA
    MDSYS
    MGMT_VIEW
    ODM
    ODM_MTR
    OE
    OLAPSYS
    ORACLE_OCM
    ORDDATA
    ORDPLUGINS
    ORDSYS
    OSE$HTTP$ADMIN
    OUTLN
    PM
    SCOTT
    SH
    SI_INFORMTN_SCHEMA
    SPATIAL_CSW_ADMIN_USR
    SPATIAL_WFS_ADMIN_USR
    SYS
    SYSMAN
    SYSTEM
    TRACESRV
    MTSSYS
    OASPUBLIC
    OLAPSYS
    OWBSYS
    OWBSYS_AUDIT
    PERFSTAT
    WEBSYS
    WK_PROXY
    WKSYS
    WK_TEST
    WMSYS
    XDB
    XS$NULL

**Comment by seadba** [comment]
thanks for the fast response  - interesting - of course if you have the HR schema in your prod database you have other problems - - i  see that it will flag errors but can you also set it to more verbose output?

**Comment by laurenz** [comment]
I'm not opposed to that.

What output would you like to see? What could be interesting?

**Comment by seadba** [comment]
nothing in particular, maybe number of rows migrated, similar to impdp - i was just curious as the process seemed to finish successfully but no migration - didn not realize the examples schemas were excluded  -  anyway, it works very well - looks like it migrated the blobs as well  - thanks for fast response - good tool


btpg96=# SELECT oracle_migrate(server => 'btoradev', only_schemas=> '{BTTEST}');
NOTICE:  Creating staging schemas "ora_stage" and "pgsql_stage" ...
NOTICE:  Creating Oracle metadata views in schema "ora_stage" ...
NOTICE:  Copy definitions to PostgreSQL staging schema "pgsql_stage" ...
NOTICE:  Creating schemas ...
NOTICE:  Creating sequences ...
NOTICE:  Creating foreign tables ...
NOTICE:  Migrating table bttest.countries ...
NOTICE:  Migrating table bttest.departments ...
NOTICE:  Migrating table bttest.employees ...
NOTICE:  Migrating table bttest.job_history ...
NOTICE:  Migrating table bttest.jobs ...
NOTICE:  Migrating table bttest.locations ...
NOTICE:  Migrating table bttest.print_media ...
NOTICE:  Migrating table bttest.regions ...
NOTICE:  Creating UNIQUE and PRIMARY KEY constraints ...
NOTICE:  Creating FOREIGN KEY constraints ...
NOTICE:  Creating CHECK constraints ...
NOTICE:  Creating indexes ...
NOTICE:  Setting column default values ...
NOTICE:  Dropping staging schemas ...
NOTICE:  Migration completed with 0 errors.
 oracle_migrate
----------------
              0


                        List of relations
       Schema       |          Name           | Type  |  Owner
--------------------+-------------------------+-------+----------
 bttest             | countries               | table | migrator
 bttest             | departments             | table | migrator
 bttest             | employees               | table | migrator
 bttest             | job_history             | table | migrator
 bttest             | jobs                    | table | migrator
 bttest             | locations               | table | migrator
 bttest             | print_media             | table | migrator
 bttest             | regions                 | table | migrator
