### ISSUE TITLE
column "cust_address" of foreign table "customers" cannot be converted to or from Oracle data type

### ISSUE THREAD

**Issue by Sascha8a** [cybertec-postgresql/ora_migrator#20]
Just tried migrating the "customer_orders" sample database (found at https://github.com/oracle/db-sample-schemas/tree/master/customer_orders)

Error occurs:
`column "cust_address" of foreign table "customers" cannot be converted to or from Oracle data type`

Oracle Type: CUST_ADDRESS_TYP
New Type: xml

**Comment by laurenz** [comment]
Sorry, user defined types are not supported.

You can alter the foreign table created by `oracle_migrate_mkforeign` similar to this:

    ALTER FOREIGN TABLE ...
    OPTIONS (DROP schema, SET table `(SELECT col1, col2, ..., CAST(cust_address AS varchar2), ... FROM customers)');

Then migrate the table.
