### ISSUE TITLE
Lines for view definition cut in pgsql_stage

### ISSUE THREAD

**Issue by beton-mischa** [cybertec-postgresql/ora_migrator#23]
Hi @laurenz 

i am not sure why, but i noticed oracle_migrate_prepare() cut a line in a view's definition.
The oracle view contains something like : 

> FROM TABLE_A LEFT OUTER JOIN TABLE_B
> ON ( TABLE_B.COLUMN_X = TABLE_A.COLUMN_X
> )

In the view's definition in pgsql_stage.views TABLE_A.COLUMN_X was cut short and happened to result in another **valid** column name in TABLE_A.

If the two columns wouldn't have been of two different types (NUMBER(10,0) and VARCHAR2(255 BYTE) i would not even have got an error message.

Have a nice day

**Comment by laurenz** [comment]
Does the view show up with the truncated definition in the foreign table `views` in the Oracle staging schema (by default `ora_stage`)?

Does the behaviour change if you use a bigger `max_long` parameter?

**Comment by beton-mischa** [comment]
Hello ,

i am really sorry, i tried to test you suggestions and noticed it was my fault.
I missed an error in the script which had already gone a step further than just oracle_migrate_prepare() and also brought in the truncated line in the view's definition.
So, nerver mind, ora_migrator is a great tool.
