### ISSUE TITLE
db_migrator documentation

### ISSUE THREAD

**Issue by kennytanms** [cybertec-postgresql/ora_migrator#24]
Hello,

It is mentioned on https://github.com/cybertec-postgresql/ora_migrator that there is a db_migrator documentation

> Please read the db_migrator documentation for usage instructions

However, I cannot find this documentation. Where can I download this documentation ?

Best regards,
Kenny Tan

**Comment by laurenz** [comment]
There is a link at the very top of the README:
https://github.com/cybertec-postgresql/ora_migrator
