### ISSUE TITLE
Error while running ora_migrator

### ISSUE THREAD

**Issue by Saurabh-704** [cybertec-postgresql/ora_migrator#26]
Hello All !
I installed ora_migrator extension. And I ran the command to migrate, but I am getting error.
<img width="472" alt="ora_migrator" src="https://user-images.githubusercontent.com/47383623/89994397-b1449d80-dca5-11ea-9838-ff76713de8cc.png">

Note - I have my postgres and oracle in linux env and I have connected both db remotely in my local through pgAdmin and SQLdeveloper.

Can anyone please help me with this issue...like I need to add something else or like something I am lagging?
Thanks in Advance!!

**Comment by Saurabh-704** [comment]
Hello All!!
After installing ora_migrater I have ran following command -

- create server ORADB2 foreign data wrapper oracle_fdw options (dbserver '//0.0.0.0:1521/SID');
Here 0.0.0.0 = host Ip 

Then I have given -
GRANT USAGE ON FOREIGN SERVER oradb2 to Postgres;

And then I ran -
CREATE USER MAPPING FOR postgres server ORADB2 options (user 'system', password 'XYZ');

And when I am running -
SELECT oracle_diag('oradb2')
I am getting output as -
<img width="404" alt="ora_migrator1" src="https://user-images.githubusercontent.com/47383623/90039588-7b72d980-dce4-11ea-8ab7-b5f11b039809.png">

And then I am also checking - 
SELECT oracle_diag();
I am getting -
<img width="517" alt="ora_migrator3" src="https://user-images.githubusercontent.com/47383623/90040151-3c915380-dce5-11ea-8e05-7489b9a4e261.png">


Till this everything is ok...but when I am running-
SELECT oracle_migrate(server => 'oradb2', only_schemas => '{APPS}');

I am getting error -
<img width="443" alt="ora_migrator2" src="https://user-images.githubusercontent.com/47383623/90039819-cd1b6400-dce4-11ea-81f0-51e836f78326.png">

Can someone please help me with this that why I am getting error here? and what should I do to resolve this thing ?

**Comment by laurenz** [comment]
Which version did you install? an old version that does not use db_migrator`?

What do you get for `\dx` in `psql`?

**Comment by Saurabh-704** [comment]
Hello @laurenz . Thank you for your response. I installed the latest ora_migrator that is something 0.9.2.sql .
But now like while troubleshooting that issue what I did is II drop the extension and again ran "create extension ora_migrator"
so it is giving me error -

ERROR: function "adjust_to_bigint" already exists with same argument types
SQL state: 42723

And when I am trying to drop that function, then it is asking me to first drop db_migrator and then drop that function.
So I dont know it will right approach or not. 

@laurenz can you please help me with this ?

**Comment by laurenz** [comment]
This seems to be a version problem; see #27.

Either use the old version of ora_migrator *without* db_migrator, then you migrate with `oracle_migrate`.
Or use the latest development version with db_migrator, then you migrate with `db_migrate`.

Sorry that this is confusing; ora_migrator underwent a major restructuring, with the idea to use the same infrastructure to migrate data from any database for which there is a foreign data wrapper.

**Comment by Saurabh-704** [comment]
Thank you @laurenz for your time. #27 was resolved. 

Now let me check with that \dx+ command in pgsql for this #26 issue.

**Comment by Saurabh-704** [comment]
Hello @laurenz 
When I am running \dx+ I am getting this as a output -

EcommMig=# \dx+
              Objects in extension "db_migrator"
                      Object description
---------------------------------------------------------------
 function adjust_to_bigint(numeric)
 function db_migrate_constraints(name,name)
 function db_migrate_finish(name,name)
 function db_migrate_functions(name,name)
 function db_migrate_mkforeign(name,name,name,name,jsonb)
 function db_migrate(name,name,name,name,name[],jsonb,boolean)
 function db_migrate_prepare(name,name,name,name,name[],jsonb)
 function db_migrate_refresh(name,name,name,name[])
 function db_migrate_tables(name,name,boolean)
 function db_migrate_triggers(name,name)
 function db_migrate_views(name,name)
 function materialize_foreign_table(name,name,boolean,name)
(12 rows)

                      Objects in extension "dblink"
                           Object description
-------------------------------------------------------------------------
 foreign-data wrapper dblink_fdw
 function dblink_build_sql_delete(text,int2vector,integer,text[])
 function dblink_build_sql_insert(text,int2vector,integer,text[],text[])
 function dblink_build_sql_update(text,int2vector,integer,text[],text[])
 function dblink_cancel_query(text)
 function dblink_close(text)
 function dblink_close(text,boolean)
 function dblink_close(text,text)
 function dblink_close(text,text,boolean)
 function dblink_connect(text)
 function dblink_connect(text,text)
 function dblink_connect_u(text)
 function dblink_connect_u(text,text)
 function dblink_current_query()
 function dblink_disconnect()
 function dblink_disconnect(text)
 function dblink_error_message(text)
 function dblink_exec(text)
 function dblink_exec(text,boolean)
 function dblink_exec(text,text)
 function dblink_exec(text,text,boolean)
 function dblink_fdw_validator(text[],oid)
 function dblink_fetch(text,integer)
 function dblink_fetch(text,integer,boolean)
 function dblink_fetch(text,text,integer)
 function dblink_fetch(text,text,integer,boolean)
 function dblink_get_connections()
 function dblink_get_notify()
 function dblink_get_notify(text)
 function dblink_get_pkey(text)
--More--

**Comment by laurenz** [comment]
Looks good. But I was wondering about `\dx`, not `\dx+`, so that we see the schema where the extension is installed.
This schema should be on your `search_path`.

**Comment by Saurabh-704** [comment]
Soory @laurenz for the inconvenience.
This is the result for \dx -

EcommMig=# \dx
                                                     List of installed extensions
     Name      | Version |   Schema   |                                          Description
---------------+---------+------------+-----------------------------------------------------------------------------------------------
 db_migrator   | 0.9.0   | public     | Tools to migrate other databases to PostgreSQL
 dblink        | 1.2     | public     | connect to other PostgreSQL databases from within a database
 ora_migrator  | 0.9.2   | public     | Tools to migrate Oracle databases to PostgreSQL
 oracle_fdw    | 1.1     | public     | foreign data wrapper for Oracle access
 orafce        | 3.13    | public     | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 pg_trgm       | 1.4     | HR2        | text similarity measurement and index searching based on trigrams
 pgtap         | 1.1.0   | public     | Unit testing for PostgreSQL
 plpgsql       | 1.0     | pg_catalog | PL/pgSQL procedural language
 plpgsql_check | 1.11    | public     | extended check for plpgsql functions
 uuid-ossp     | 1.1     | AR         | generate universally unique identifiers (UUIDs)
(10 rows)

**Comment by laurenz** [comment]
Yes, that looks good now. Is everything working?

**Comment by Saurabh-704** [comment]
No @laurenz . I am getting same error.
Let me explain you what exactly I did-

1) I created server -

create server ORADB2 foreign data wrapper oracle_fdw options (dbserver '//0.0.0.0:1521/SID');

Here Here 0.0.0.0 = host Ip

2) Then - 

GRANT USAGE ON FOREIGN SERVER oradb2 to Postgres;

Here postgres is my postgres user.

3) CREATE USER MAPPING FOR postgres server ORADB2 options (user 'system', password 'Password123');

Here postgres = postgres user.
       system =  oracle user
      Password123= Password for oracle system user.

4)Then  I ran -
   SELECT oracle_migrate(server => 'oradb2', only_schemas => '{APPS}');

    Here APPS is schema inside oracle.
And at this stage i got error, which I was getting at starting.

These are the steps which I followed till now.
So is there anything which I am missing or what?

**Comment by laurenz** [comment]
Right, it is called `db_migrate` in the new version.

**Comment by Saurabh-704** [comment]
Thank you @laurenz for the response. I am bit confused actually. Like I installed db_migrate extension already, so like I have to install plugin also now?!. If yes then like where can I get this plugin details and installation part?

As you asked to go through db_migrator documentation so I have seen one plugin API section there https://github.com/cybertec-postgresql/db_migrator#plugin-api 
Do I need to follow this for installation or some other link I have to follow?!

Thanks in advance!

**Comment by laurenz** [comment]
You need to install db_migrator and *the development version* of ora_migrator.

Then proceed as indicated by the [showcase](https://github.com/cybertec-postgresql/db_migrator#showcase).

**Comment by Saurabh-704** [comment]
Hello @laurenz . I already installed db_migrator .
I also installed ora_migrator from the link - https://github.com/cybertec-postgresql/ora_migrator

In previous msgs also I have shown the screenshot - https://github.com/cybertec-postgresql/ora_migrator/issues/26#issuecomment-673384515

**Comment by laurenz** [comment]
Then you have installed the plugin - that plugin is ora_migrator (there might be plugins for other database in the future if someone writes them).

My previous comment pointed you to the documentation that tell you to run `db_migrate`.

There is no function called `oracle_migrate`.

**Comment by Saurabh-704** [comment]
Yes @laurenz . I got that thing, actually I got bit confused as you asked me to download plugin. Sorry for the inconvenience from my side. 

I followed that showcase one , I got some error again-
<img width="616" alt="sed2" src="https://user-images.githubusercontent.com/47383623/90153453-a1f94900-dda6-11ea-9937-d4b2b57b1c77.png">

**Comment by Saurabh-704** [comment]
Hello @laurenz . For previous error I dropped the fdw_stage schema. And it worked fine.
But just need to confirm one thing that, after importing the schema , I have one table in which I have some data.
But after importing the schema from oracle I am only able to see structure of table not the data. 
Let me attach screenshot also-
<img width="385" alt="db_2" src="https://user-images.githubusercontent.com/47383623/90212024-f71d7500-de0f-11ea-8dbd-a8ae673f9f94.png">

And when I am doing select count(*) from test.emp, I am getting -
<img width="311" alt="db_3" src="https://user-images.githubusercontent.com/47383623/90212098-1f0cd880-de10-11ea-94de-0d0689dfa777.png">

So just wanted to confirm that for importing data we have to run different command or when we run that schema conversation command that time only it will do all the things?!

**Comment by Saurabh-704** [comment]
Hello @laurenz . Thank you for your time. I troubleshooted that issue, and got resolved.
Thank you once again for your time.

**Comment by laurenz** [comment]
Glad it worked eventually!
