### ISSUE TITLE
Getting issue after recreating extension

### ISSUE THREAD

**Issue by Saurabh-704** [cybertec-postgresql/ora_migrator#27]
Hello @laurenz 
As I was having same trouble with ora_migrator so I drop the extension and again ran "create extension ora_migrator" 
so it is giving me error -

ERROR:  function "adjust_to_bigint" already exists with same argument types
SQL state: 42723

And when I am trying to drop that function, then it is asking me to first drop db_migrator and then drop that function.
So I dont know it will right approach or not.

@laurenz Can you please help me with this?!

**Comment by laurenz** [comment]
The function `adjust_to_bigint` used to be part of ora_migrator before it became a db_migrator plugin. Now the function is part of db_migrator.

So I assume that you are trying to use an old version of ora_migrator with the current db_migrator.

To fix the problem, use the latest development version of ora_migrator.

**Comment by Saurabh-704** [comment]
Thank you @laurenz for your response. What I did as I was getting issue with new version, so I tried to install previous older  version and then from drop the ora_migrator extension and then again ran create command and than I got that issue.

I tried going inside /usr/pgsql-12/share/extension and tried removing that older ora_migrator extension by giving "rm ora_migrator.0.9.0.1.sql" but it seems that its not removing and not working. 

So can you please help me like how to uninstall older version so that I can use latest version?!

Thanks in advance!

**Comment by laurenz** [comment]
The recommended way is to run `make uninstall` while in the `ora_migrator` directory.

You must be `root` to remove a file from `/usr/pgsql-12/share/extension`, either manually or with `make uninstall`.

**Comment by Saurabh-704** [comment]
Thank you @laurenz . It ran without any issue now.
