### ISSUE TITLE
SCOTT schema

### ISSUE THREAD

**Issue by MichaelDBA** [cybertec-postgresql/ora_migrator#3]
It appears that ora_migrator excludes explicitly some internal schemas.  I can understand the rationale for most of them since they are more system type objects, but SCOTT is a good example user schema, and is useful for testing oracle to postgresql migrations.  Can you not exclude the SCOTT schema or allow one to specify it for a migration?

**Comment by laurenz** [comment]
This appears to be the same problem as issue #2.

Two people complaining about the same thing means something, though I am not certain what. Probably that people are running tests.

I am kind of reluctant to allow these schemas. I am afraid that they will cause more problems when migrating production databases than they will help with testing.

What is the problem with choosing a different schema for testing?

**Comment by MichaelDBA** [comment]
hmmm, that last sentence from you sounds "hunky dory".  But just wondering why not have a schema exclude or include option for user type schemas like HR and SCOTT and disallow the use of the system schemas internally like you do now?

**Comment by laurenz** [comment]
I didn't mean to sound lackadaisical...

There already *is* an option to specify which schemas you want, so I think it would not be necessary to introduce one.

I thought about it, and there is nothing dangerous about migrating these schemas by default. People probably don't have them in production, and they are convenient for testing.

**Comment by laurenz** [comment]
Done. Is that ok for you?

**Comment by MichaelDBA** [comment]
Fantastic!  Thanks as usual for your timely responses!
