### ISSUE TITLE
Function oracle_replication_catchup can't work with table with only one column which is primary key

### ISSUE THREAD

**Issue by lemrouch** [cybertec-postgresql/ora_migrator#33]
The code in _ora_migrator--0.9.2.sql:1370_ is written to exclude primary key from the SET which causes
```
db=# SELECT public.oracle_replication_catchup();
ERROR:  syntax error at or near "WHERE"
LINE 4: WHERE value = ($1).value
        ^
QUERY:  PREPARE upd_stmt("__Log_schema/table") AS
UPDATE schema.table SET
   
WHERE value = ($1).value
```
if the table has only one column which is primary key.
Do you think it's good idea to get rid of the ELSE and include all columns into _upd_stmt_?

**Comment by laurenz** [comment]
You are right. Thanks for the report!
Could you test if that fix works for you?

**Comment by lemrouch** [comment]
Yes, it works now.
Thanks a lot!
