### ISSUE TITLE
Replication does not catchup sequences

### ISSUE THREAD

**Issue by lemrouch** [cybertec-postgresql/ora_migrator#35]
Hi,
I think there is no update of sequences after initial _db_migrate_mkforeign_.
Therefore I would suggest something like:
```
FOR sch, seq, lastval IN
  SELECT SELECT schema, sequence_name, last_number FROM sequences
LOOP
  BEGIN
    EXECUTE format('ALTER SEQUENCE %I.%I START %s', sch, seq, lastval + 1);
  EXCEPTION
    WHEN others THEN
    /* turn the error into a warning */
    GET STACKED DIAGNOSTICS
    errmsg := MESSAGE_TEXT,
    detail := PG_EXCEPTION_DETAIL;
    RAISE WARNING 'Error altering sequence %.%', sch, seq
      USING DETAIL = errmsg || coalesce(': ' || detail, '');
        format(
          E'INSERT INTO %I.migrate_log\n'
          '   (operation, schema_name, object_name, failed_sql, error_message)\n'
          'VALUES (\n'
          '   ''alter sequence'',\n'
          '   %L,\n'
          '   %L,\n'
          '   %L,\n'
          '   %L\n'
          ')',
          pgstage_schema,
          sch,
          seq,
          format('ALTER SEQUENCE %I.%I START %s',
            sch, seq, lastval + 1),
            errmsg || coalesce(': ' || detail, '')
          );
  END;
END LOOP;
```
but I'm not sure how would you like to include this.

What do you think of function _oracle_catchup_sequences_ called from in _oracle_replication_finish_ or documentation update of the last call to _oracle_replication_catchup_ in [Replication](https://github.com/cybertec-postgresql/ora_migrator#replication)?

**Comment by laurenz** [comment]
Yes, that is a missing feature, and ora_migrator could use some improvement here. Thank you for bringing it up!

I think that this should happen during `oracle_replication_catchup`. I'd say there should be a function `oracle_catchup_sequence` similar to `oracle_catchup_table` that simply queries the current value from the `sequences` foreign table. `oracle_replication_catchup` should then loop through all sequences and call `oracle_catchup_sequence` for each.

Your code is a good starting point. I wouldn't do any error handling, and errors should just propagate. Also, the PostgreSQL sequence should be set with `setval()` &ndash; altering the start value like in your example isn't the correct thing to do.

Do you feel like writing a patch for this? I won't have much time next week.

**Comment by lemrouch** [comment]
Hi,
I'm a little bit confused [by](https://github.com/cybertec-postgresql/ora_migrator/blob/master/ora_migrator--0.9.2.sql#L1467)
```
      SELECT s.schema, t.table_name
      FROM schemas AS s
         JOIN tables AS t USING (schema)
      WHERE t.migrate
```
What is the joined _schemas_ good for?
Insert into both _schemas_ and _tables_ is done with _USING only_schemas_ so nothing should be extra nor missing in the table and the only extra column _orig_schema_ in _schemas_ table is not used.
Therefore
```
      SELECT schema, table_name
      FROM tables
      WHERE migrate
```
should be enough, right?

**Comment by laurenz** [comment]
Yes, that should be unnecessary. On the other hand, it does not harm either, does it?
I am not sure why I wrote it like that. Perhaps I was worried that somebody would edit schema names in the PostgreSQL stage, not sure.

**Comment by lemrouch** [comment]
It's not as straightforward as I thought.
I have to either call _db_migrate_refresh()_ to update _pgsql_stage.sequences_ or propagate _staging_schema_ through as parameter of _oracle_replication_catchup()_ to get to _fdw_stage.sequences_, right?

**Comment by laurenz** [comment]
You are right. I think having the staging schema as parameter is the good way.

**Comment by lemrouch** [comment]
I know the _oracle_tolower()_ will result into full table scan but I know no simple way to figure out the original sequence name from _pgstage_schema.sequence_name_.

**Comment by laurenz** [comment]
If a sequential scan on the table of sequences is a performance problem, something much be quite weird...

**Comment by lemrouch** [comment]
I agree.
Are you satisfied with the PR then?

**Comment by laurenz** [comment]
Yes, and thank you.
Do you think you can add something to the regression tests to exercise this?

**Comment by lemrouch** [comment]
I can try to.
