### ISSUE TITLE
Function oracle_replication_catchup don't update column without pk/uk

### ISSUE THREAD

**Issue by scapy11** [cybertec-postgresql/ora_migrator#43]
Testing the replication of update from one table with 2 columns, one with pk and another column without, the function oracle_replication_catchup , didn't update the table:

```shell
Oracle db:
desc test.rep_sync_test;
 Name                                                                                                  Null?    Type
 ----------------------------------------------------------------------------------------------------- -------- --------------------------------------------------------------------
 ID                                                                                                    NOT NULL NUMBER
 SOMETEXT            

tried update id 55:
update test.rep_sync_test set sometext='test55556' where id=55;

PG db
select oracle_replication_catchup (
staging_schema  => 'pgtest_fdw',
pgstage_schema => 'pgtest_stage'
);

select * from test.rep_sync_test ;
 id | sometext
----+----------
  1 | test1
  2 | test2
  3 | test3
 33 | test3
 33 | test33
  4 | test4
 44 | test4
 55 | test5        <<<<<<< didn't update 

data from replication table log in PG

select * from pgftest_stage."__Log_test/rep_sync_test" ;
 __Operation |           __Time           | id | sometext
-------------+----------------------------+----+-----------
 I           | 2024-03-14 11:40:24.081132 |  3 | test3
 D           | 2024-03-14 11:42:33.220546 |  3 | NULL
 I           | 2024-03-14 11:42:33.220652 | 33 | test3
 U           | 2024-03-14 11:43:45.111501 | 33 | test33
 U           | 2024-03-14 11:44:59.122514 | 33 | test333
 U           | 2024-03-14 11:48:45.917732 | 33 | test3333
 I           | 2024-03-14 11:49:59.003516 |  4 | test4
 D           | 2024-03-14 11:50:20.444307 |  4 | NULL
 I           | 2024-03-14 11:50:20.444407 | 44 | test4
 D           | 2024-03-14 12:05:28.499586 | 44 | NULL
 I           | 2024-03-14 12:09:37.934051 |  5 | test5
 D           | 2024-03-14 12:10:36.960318 | 33 | NULL
 D           | 2024-03-14 12:12:08.554941 |  5 | test5
 I           | 2024-03-14 12:12:52.275783 |  5 | test5
 D           | 2024-03-14 12:13:16.697013 |  5 | test5
 I           | 2024-03-14 12:13:16.697108 | 55 | test5
 U           | 2024-03-14 12:16:03.726926 | 55 | test5555
 U           | 2024-03-14 12:29:23.749421 | 55 | test55556

````

The Update PK/UK it was possible after changed the trigger pick the OLD values of columns, because it add NULL in not constraints column.

Any ideia how to resolve the issue?

**Comment by laurenz** [comment]
What is in `pgtest_stage."__ReplicationStart"` and `pgtest_stage."__ReplicationEnd"`?

**Comment by scapy11** [comment]
Inside "__Replication%" tables is the timestamp for the last time call the function and in other the last timestamp in oracle transaction and is always updating.

To resolve the update, as I don't understand to much of pgplsql, in Oracle side changed the trigger in Update to do a delete and save the OLD values and an Insert with NEW values. like his in postgres when call the function it delete and insert the row with update data

**Comment by scapy11** [comment]
Thanks for your reply and for this tool too.
No weirdness trigger in Postgres table, I only created to test this table to figure out the update issue.

Test with `RAISE NOTICE` as you mention in several lines with variables to 
Here some output when try to update:

```shell
NOTICE:  Insert Stat ... value ... is PREPARE upd_stmt("__Log_test/rep_sync_test") AS
UPDATE test.rep_sync_test SET
   id = ($1).id,
   sometext = ($1).sometext,
   sometext2 = ($1).sometext2
NOTICE:  Inser Value ... value ... is
WHERE id = ($1).id AND sometext = ($1).sometext AND sometext2 = ($1).sometext2
NOTICE:  Del Stat ... value ... is PREPARE upd_stmt("__Log_common/rep_sync_test") AS
UPDATE test.rep_sync_test SET
   id = ($1).id,
   sometext = ($1).sometext,
   sometext2 = ($1).sometext2
NOTICE:  Del Where ... value ... is
WHERE id = ($1).id AND sometext = ($1).sometext AND sometext2 = ($1).sometext2
NOTICE:  UPDATE Stat exec ... value ... is (U,"2024-03-14 17:06:24.985915",1,test1,test22212299900)
 oracle_replication_catchup
----------------------------

(1 row)

Time: 377.619 ms
select * from test.rep_sync_test;
 id | sometext | sometext2
----+----------+-----------
  1 | test1    | test1
(1 row)

```

As you can see, after the `oracle_catchup_table()` the data is not update with the new value `test22212299900`

**Comment by laurenz** [comment]
The output is a bit unclear. Perhaps you could apply instead these two debugging statements:

```diff
diff --git a/ora_migrator--1.1.0.sql b/ora_migrator--1.1.0.sql
index 1c0feaa..00162e2 100644
--- a/ora_migrator--1.1.0.sql
+++ b/ora_migrator--1.1.0.sql
@@ -1557,6 +1557,7 @@ BEGIN
    /* prepare the statements */
    EXECUTE v_ins_stmt || v_values || ')';
    EXECUTE v_upd_stmt || v_where_clause;
+   RAISE NOTICE E'Prepared update statement is:\n%', v_upd_stmt || v_where_clause;
    EXECUTE v_del_stmt || v_where_clause;
 
    /* loop through the changes and apply them */
@@ -1584,6 +1585,7 @@ BEGIN
          WHEN v_op = 'I' THEN
             EXECUTE format('EXECUTE ins_stmt(%L)', v_rec);
          WHEN v_op = 'U' THEN
+            RAISE NOTICE '-> ', format('EXECUTE upd_stmt(%L)', v_rec);
             EXECUTE format('EXECUTE upd_stmt(%L)', v_rec);
          WHEN v_op = 'D' THEN
             EXECUTE format('EXECUTE del_stmt(%L)', v_rec);
```

Then run your test case again and show me the output.

Can you also show me the output of

```
\d pgtest_stage."__Log_test/rep_sync_test"
```

so that I can see that the table is defined correctly.

**Comment by scapy11** [comment]
Table Log definition:

 \d pgtest_stage."__Log_test/rep_sync_test"
                 Foreign table "pgtest_stage.__Log_test/rep_sync_test"
   Column    |            Type             | Collation | Nullable | Default | FDW options
-------------+-----------------------------+-----------+----------+---------+--------------
 __Operation | character varying(1)        |           | not null |         |
 __Time      | timestamp without time zone |           | not null |         | (key 'true')
 id          | numeric                     |           | not null |         | (key 'true')
 sometext    | character varying(20)       |           |          |         |
 sometext2   | character varying(20)       |           |          |         |
Server: oracle_test
FDW options: (schema 'TEST', "table" '__Log_REP_SYNC_TEST', readonly 'true')


Executing catchup:

select oracle_replication_catchup (
staging_schema  => 'pgtest_fdw',
pgstage_schema => 'pgtest_stage'
);
NOTICE:  Prepared update statement is:\nPREPARE upd_stmt("__Log_test/rep_sync_test") AS
UPDATE test.rep_sync_test SET
   id = ($1).id,
   sometext = ($1).sometext,
   sometext2 = ($1).sometext2
WHERE id = ($1).id AND sometext = ($1).sometext AND sometext2 = ($1).sometext2
 oracle_replication_catchup
----------------------------

The RAISE NOTICE '-> ', format('EXECUTE upd_stmt(%L)', v_rec); give me error, when try to add in procedure. give too many values.

**Comment by laurenz** [comment]
Sorry, the second statement should have been

    RAISE NOTICE '-> %', format('EXECUTE upd_stmt(%L)', v_rec);

**Comment by scapy11** [comment]
Thanks, I tried to play around with RAISE, but didn't 

```shell
select oracle_replication_catchup (
staging_schema  => 'pgtest_fdw',
pgstage_schema => 'pgtest_stage'
);
NOTICE:  Prepared update statement is:\nPREPARE upd_stmt("__Log_test/rep_sync_test") AS
UPDATE test.rep_sync_test SET
   id = ($1).id,
   sometext = ($1).sometext,
   sometext2 = ($1).sometext2
WHERE id = ($1).id AND sometext = ($1).sometext AND sometext2 = ($1).sometext2
NOTICE:  -> EXECUTE upd_stmt('(U,"2024-03-15 13:10:08.686005",3,test33334552,test33)')
 oracle_replication_catchup
----------------------------

(1 row)

select * from test.rep_sync_test ;
 id | sometext | sometext2
----+----------+-----------
  3 | test33   | test33    <<< still same value

```

**Comment by laurenz** [comment]
I think I see why there are no changes. The executed statement is

```
UPDATE test.rep_sync_test SET
   id = NUMERIC '3',
   sometext = VARCHAR 'test33334552',
   sometext2 = VARCHAR 'test33'
WHERE id = NUMERIC '3' AND sometext = VARCHAR 'test33334552', AND sometext2 = VARCHAR 'test33';
```

and that statement won't change anything, since the value of `sometect` is different.

The question is why the additional columns are in the `WHERE` clause. According to the code, that should only happen if all three columns are part of the primary key. What is the primary key of the Oracle table?

Can you show me

    SELECT keys.schema,
           keys.table_name,
           keys.column_name,
    FROM pgftest_stage.keys
    WHERE keys.is_primary
      AND schema = 'text'
      AND table_name = 'rep_sync_test';

**Comment by scapy11** [comment]
The  `WHERE` clause can bring the others columns,  maybe forgot to undo what I made in Oracle trigger side.
When it used only the PK column put the other columns as `NULL`, and didn't change the data.
I will undo the tigger and check again.

The id column is the pkey.

```
 schema |  table_name   | column_name
--------+---------------+-------------
 test | rep_sync_test | id
(1 row)
```

**Comment by laurenz** [comment]
I don't think that the Oracle trigger has a problem, although you shouldn't modify it. ora_migrator creates those triggers.

My concern is the strange `UPDATE` statement. The statement is constructed from the results of the following query:

```
SELECT c.column_name,
       c.orig_column,
       c.type_name,
       c.orig_type,
       coalesce(k.is_pkey, FALSE)
FROM pgftest_stage.columns AS c
   LEFT JOIN (SELECT schema,
                     table_name,
                     column_name,
                     TRUE AS is_pkey
              FROM pgftest_stage.keys
              WHERE is_primary) AS k
      USING (schema, table_name, column_name)
WHERE schema = 'test'
  AND table_name = 'rep_sync_test'
ORDER BY c.position;
```

Can you please send me the results of that query?

**Comment by scapy11** [comment]
Output: 

```
 column_name | orig_column |       type_name       |  orig_type   | coalesce
-------------+-------------+-----------------------+--------------+----------
 id          | ID          | numeric               | NUMBER       | t
 sometext    | SOMETEXT    | character varying(20) | VARCHAR2(20) | f
 sometext2   | SOMETEXT2   | character varying(20) | VARCHAR2(20) | f
(3 rows)
```

I recreate again from the scratch the staging schemas and recreate the trigger and log table in Oracle side.

```shell
Initial data:
select * from test.rep_sync_test ;
 id | sometext | sometext2
----+----------+-----------
  1 | test1    | test1
  2 | test2    | test2
  3 | test3    | test3

Oracle -> update common.rep_sync_test set sometext='test333' where id=3;

PG-> select oracle_replication_catchup ();
NOTICE:  Prepared update statement is:\nPREPARE upd_stmt("__Log_test/rep_sync_test") AS
UPDATE test.rep_sync_test SET
   id = ($1).id,
   sometext = ($1).sometext,
   sometext2 = ($1).sometext2
WHERE id = ($1).id AND sometext = ($1).sometext AND sometext2 = ($1).sometext2
NOTICE:  -> EXECUTE upd_stmt('(U,"2024-03-15 16:09:03.245538",3,test333,test3)')
 oracle_replication_catchup
----------------------------

(1 row)

Time: 60.294 ms
select * from test.rep_sync_test ;
 id | sometext | sometext2
----+----------+-----------
  1 | test1    | test1
  2 | test2    | test2
  3 | test3    | test3   << no update done


Oracle -> update common.rep_sync_test set id=33 where sometext='test333';
PG  -> select oracle_replication_catchup ();
NOTICE:  Prepared update statement is:\nPREPARE upd_stmt("__Log_test/rep_sync_test") AS
UPDATE test.rep_sync_test SET
   id = ($1).id,
   sometext = ($1).sometext,
   sometext2 = ($1).sometext2
WHERE id = ($1).id AND sometext = ($1).sometext AND sometext2 = ($1).sometext2
 oracle_replication_catchup
----------------------------

(1 row)

Time: 55.772 ms
select * from test.rep_sync_test ;
 id | sometext | sometext2
----+----------+-----------
  1 | test1    | test1
  2 | test2    | test2
  3 | test3    | test3
 33 | test333  | test3   <<< added new row

```

**Comment by laurenz** [comment]
I am a bit confused. Are you saying it is working now?
It looks like you are updating an Oracle row that does not even exist.

My suggestion is that you drop all Oracle and PostgreSQL objects ad start from scratch.
If the Oracle and the PostgreSQL table have already drifted apart (due to a bug or whatever), catchup cannot work any more.

What is still unexplained is why the `WHERE` clause of the `UPDATE` statement has all three columns, if your query ascertained that only `id` is the primary key.

Here is a patch with one more debugging line, perhaps that can shed some light:

```diff
diff --git a/ora_migrator--1.1.0.sql b/ora_migrator--1.1.0.sql
index 1c0feaa..2de4272 100644
--- a/ora_migrator--1.1.0.sql
+++ b/ora_migrator--1.1.0.sql
@@ -1523,6 +1523,7 @@ BEGIN
         AND c.table_name = $2
       ORDER BY c.position
    LOOP
+      RAISE NOTICE '-> Columns %, primary key %', v_colname, v_is_pkey;
       /* "v_has_pkey" will end up TRUE if there is a primary key column */
       v_has_pkey := v_has_pkey OR v_is_pkey;
 
@@ -1557,6 +1558,7 @@ BEGIN
    /* prepare the statements */
    EXECUTE v_ins_stmt || v_values || ')';
    EXECUTE v_upd_stmt || v_where_clause;
+   RAISE NOTICE E'Prepared update statement:%', v_upd_stmt || v_where_clause;
    EXECUTE v_del_stmt || v_where_clause;
 
    /* loop through the changes and apply them */
@@ -1584,6 +1586,7 @@ BEGIN
          WHEN v_op = 'I' THEN
             EXECUTE format('EXECUTE ins_stmt(%L)', v_rec);
          WHEN v_op = 'U' THEN
+            RAISE NOTICE '-> %', format('EXECUTE upd_stmt(%L)', v_rec);
             EXECUTE format('EXECUTE upd_stmt(%L)', v_rec);
          WHEN v_op = 'D' THEN
             EXECUTE format('EXECUTE del_stmt(%L)', v_rec);
```

**Comment by laurenz** [comment]
Any news on this?

**Comment by scapy11** [comment]
Hi, sorry for the delay, only today tested.
After remove and install from scratch, it replicate correctly.
Maybe some changes made and had this  situation..
Thanks for your help.

**Comment by laurenz** [comment]
Thanks for the feedback.
