### ISSUE TITLE
 function regexp_match(text, unknown) does not exist

### ISSUE THREAD

**Issue by charan4599** [cybertec-postgresql/ora_migrator#7]
hello,
i installed ora_migrator tool and am able to import couple of schemas from oracle to postgres but i hit road block when tried to migrate bigger schema

Here is the error what i see. Do you know about this error?
iamaws=#  SELECT oracle_migrate(server => 'oracle_goldpg', only_schemas => '{CATCLIE}');
NOTICE:  Creating staging schemas "ora_stage" and "pgsql_stage" ...
NOTICE:  Creating Oracle metadata views in schema "ora_stage" ...
NOTICE:  Copy definitions to PostgreSQL staging schema "pgsql_stage" ...
ERROR:  function regexp_match(text, unknown) does not exist
LINE 1: SELECT unnest(regexp_match(s, '"([^"]*)"'))
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT unnest(regexp_match(s, '"([^"]*)"'))
CONTEXT:  PL/pgSQL function translate_expression(text) line 4 at FOR over SELECT rows
PL/pgSQL function public.oracle_migrate_refresh(name,name,name,name[],integer) line 111 at assignment
PL/pgSQL function public.oracle_migrate_prepare(name,name,name,name[],integer) line 245 at RETURN
PL/pgSQL function public.oracle_migrate(name,name,name,name[],integer) line 15 at assignment
iamaws=#

**Comment by laurenz** [comment]
The problem is probably that you are using PostgreSQL 9.6 or earlier, where `regexp_match` doesn't exist.
But I realize that my code doesn't do what it should do anyway.

Will fix.
