### ISSUE TITLE
ORA error while importing schema

### ISSUE THREAD

**Issue by charan4599** [cybertec-postgresql/ora_migrator#8]
Hello @laurenz 
Thanks for your help on previous issue, now i run into another issue. it is giving ORA-01406 error while importing schema

iamaws=# SELECT oracle_migrate(server => 'oracle_goldpg', only_schemas => '{DBO}');
NOTICE:  Creating staging schemas "ora_stage" and "pgsql_stage" ...
NOTICE:  Creating Oracle metadata views in schema "ora_stage" ...
NOTICE:  Copy definitions to PostgreSQL staging schema "pgsql_stage" ...
ERROR:  error fetching result: OCIStmtFetch2 failed to fetch next result row
DETAIL:  ORA-01406: fetched column value was truncated
CONTEXT:  SQL statement "INSERT INTO views (schema, view_name, definition, oracle_def)
   SELECT oracle_tolower(schema),
          oracle_tolower(view_name),
          definition,
          definition
   FROM ora_stage.views
   WHERE $1 IS NULL OR schema =ANY ($1)
ON CONFLICT ON CONSTRAINT views_pkey DO UPDATE SET
   oracle_def = EXCLUDED.definition"
PL/pgSQL function public.oracle_migrate_refresh(name,name,name,name[],integer) line 213 at EXECUTE
PL/pgSQL function public.oracle_migrate_prepare(name,name,name,name[],integer) line 245 at RETURN
PL/pgSQL function public.oracle_migrate(name,name,name,name[],integer) line 15 at assignment

Charan

**Comment by charan4599** [comment]
i have got another issue while importing another schema

iamaws=# SELECT oracle_migrate(server => 'oracle_goldpg', only_schemas => '{HIPAA}');
NOTICE:  Creating staging schemas "ora_stage" and "pgsql_stage" ...
NOTICE:  Creating Oracle metadata views in schema "ora_stage" ...
NOTICE:  Copy definitions to PostgreSQL staging schema "pgsql_stage" ...
ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
CONTEXT:  SQL statement "INSERT INTO table_privs (schema, table_name, privilege, grantor, grantee, grantable)
   SELECT oracle_tolower(schema),

**Comment by laurenz** [comment]
The first problem is simple: you'll have to use a bigger `max_long` parameter for `oracle_migrate()` so that all `LONG` values in your schema can fit.

The second problem is more difficult. Can you run the following in Oracle:

    SELECT owner AS schema,
           table_name,
           privilege,
           grantor,
           grantee,
           CASE WHEN grantable = 'YES' THEN 1 ELSE 0 END grantable
    FROM dba_tab_privs
    WHERE owner = 'HIPAA';

There should be some results with the same `(schema, table_name, grantee, privilege)`.

Can you find out which ones?

**Comment by charan4599** [comment]
@laurenz 
For the first issue, do you have the syntax for using bigger max_long parameter?
I checked documentation, that parameter is available at table_level in oracle_fdw.
But here we are using schema import. if you have the syntax handy , that will be great.

Regarding second issue, i ran the sql in oracle and it fetched 5500 rows.
Not sure how do you want to see it. i can attach the file here if needed

Charan

**Comment by charan4599** [comment]
@laurenz 
i will be sending email now

Thanks
Charan

**Comment by laurenz** [comment]
Thanks.
Could you run the following query on Oracle and post the results?

    SELECT * FROM dba_tab_privs
    WHERE owner = 'HIPAA'
      AND table_name = 'PKG_X12_IMPORT'
      AND grantee = 'BENDEV_GRP'
      AND privilege = 'EXECUTE';

Looks like this is not a table.
I guess I'll have to add a `WHERE` clause to exclude such data...

**Comment by charan4599** [comment]
@laurenz 
![hipaa](https://user-images.githubusercontent.com/38915777/43843968-aea330de-9af6-11e8-8a9e-24caa75cb013.png)

here is the output and yeah its a package.

like i said, can we have only tables/constraints/indexes/sequences migrated?


Charan

**Comment by laurenz** [comment]
Working on it...

**Comment by laurenz** [comment]
Could you check if that commit fixed the problem?

Unless you edit the tables in the PostgreSQL stage, only tables (with their constraints and indexes), sequences and views will be migrated anyway.

`table_privs` is currently only there &ldquo;for your information&rdquo;, since I don't attempt to migrate privileges anyway. The idea is that you have a handy place to look what privileges have been granted in Oracle.

**Comment by charan4599** [comment]
Will give it a try and let you know

**Comment by laurenz** [comment]
I'll close the issue since I believe that the patch fixes the bug.

Don't hesitate to reopen it if I am wrong.

**Comment by charan4599** [comment]
Yes Please. Thanks for your help.
Is there any way we can change the column type of the table while migrating?


Thanks
Charan Chandika
Vitech
Office: 732-593-3653
Email: CChandika@vitechinc.com<mailto:CChandika@vitechinc.com>

**Comment by laurenz** [comment]
You can change the column data type by editing the `type_name` column in corresponding row of the `columns` table in the PostgreSQL staging schema.

This is done between the call to `oracle_migrate_prepare()` and the call to `oracle_migrate_mkforeign()`.

You can map data types if they are in the list [from the oracle_fdw documentation](https://github.com/laurenz/oracle_fdw#4-usage).
